### ISSUE TITLE
[PM] Pardo contributers call #0

### ISSUE THREAD

**Issue by soc1c** [polkablocks/pardo#3]
### Pardo Contributors Call #0

Date / Time
- Monday, November 11th, 2018
- [1pm UTC](https://savvytime.com/converter/germany-berlin-to-canada-toronto-ca-san-francisco-china-shanghai/2pm)

### Agenda
- Project kick-off
- Team intros
- _Please add your items_

First working document https://docs.google.com/document/d/1FUAzdQLdV_6is_nDJfwEhcU2HZrgpbSJPmeYKb9galk/edit#heading=h.o7f789bhp0g7

**Comment by akhanaton** [comment]
Do we have a list of potential attendees somewhere?

**Comment by soc1c** [comment]
Only https://github.com/orgs/polkablocks/people so far

**Comment by soc1c** [comment]
Moved to Wednesday the same time

**Comment by akhanaton** [comment]
I'm in. What platform are we using?

**Comment by soc1c** [comment]
Zoom or Appear.in?

**Comment by akhanaton** [comment]
Fine with either

**Comment by soc1c** [comment]
Moving to Monday, Nov/11 same time!

**Comment by akhanaton** [comment]
Should I setup a meeting or @soc1c  do you have an account you would prefer to use?

**Comment by soc1c** [comment]
https://whereby.com/soc1c

**Comment by soc1c** [comment]
attendees: 
- @qnou UX/UI/Design
- @akhanaton Dev/Backend
- @soc1c PM, Dev/Backend
- Ronin

discussed:
- introductions
- create MVP on Github pages @akhanaton 
- manage Dev tasks on Github tracker @soc1c 
- manage UX Design feedback loops on external tool TBD @qnou 
- look for an additional Dev/Frontent @soc1c maybe @SiddigZeidan can help out?
